{
 "title": "Sensor Record",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "\"SensorRecords\""
   }
  ]
 },
 "panels": [
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('second', time) as time, humidity\r\nfrom ${table}\r\norder by time desc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('second', time) as time, temperature\nfrom ${table}\norder by time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "LED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('second', time) as time, led\nfrom ${table}\norder by time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "\r\nselect date_trunc('second', time) at time zone 'utc' at time zone 'mst' as time, humidity::integer\r\nfrom ${table}\r\nORDER BY time",
     "timeField": "update_time"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "\r\nselect date_trunc('second', time) at time zone 'utc' at time zone 'mst' as time, temperature::integer\r\nfrom ${table}\r\nORDER BY time",
     "timeField": "update_time"
    }
   ]
  }
 ]
}