{
 "title": "scm-tracking-ml",
 "time": { "from": "now-6M", "to": "now+1M" },
 "templating": {
  "list": [
   { "name": "set_my_time", "label": "set_my_time", "query": "2021-01-03 00:00:00" },
   { "name": "tracking_number", "query": "YT2023921266023001" }
  ]
 },
 "panels": [
  {
   "title": "LSTM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', update_time) as time, lstm_status as status, count(*) as count_item\r\nfrom data_scm_tracking_ml\r\nWHERE lstm_status in ('IN_US', 'COMPLETED', 'RETURN_TO_SENDER')\r\nGROUP BY time, status\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "LSTM - today",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n        time,\r\n        count_item,\r\n        metric  \r\nFROM\r\n    ( SELECT item FROM (VALUES ('TRACKING_AVAILABLE'), ('TRACKING_ONLINE'), ('IN_US'),('COMPLETED'), ('RETURN_TO_SENDER')) AS X(item) ) list_items\r\n    JOIN LATERAL (\r\n    SELECT      \r\n        date_trunc('day', update_time) as time,\r\n        count(*) as count_item,\r\n                item as \"metric\"\r\n    FROM\r\n        data_scm_tracking_ml \r\n    WHERE\r\n      lstm_status = item and \r\n            date_trunc('day', update_time) = date_trunc('day', '${set_my_time}'::TIMESTAMP)\r\n    GROUP BY 1 \r\n    ORDER BY 1\r\n) foreach on true;"
    }
   ]
  },
  {
   "title": "BERT - today",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n        time,\r\n        count_item,\r\n        metric  \r\nFROM\r\n    ( SELECT item FROM (VALUES ('TRACKING_AVAILABLE'), ('TRACKING_ONLINE'), ('IN_US'),('COMPLETED'), ('RETURN_TO_SENDER')) AS X(item) ) list_items\r\n    JOIN LATERAL (\r\n    SELECT      \r\n        date_trunc('day', update_time) as time,\r\n        count(*) as count_item,\r\n                item as \"metric\"\r\n    FROM\r\n        data_scm_tracking_ml \r\n    WHERE\r\n      bert_status = item and date_trunc('day', update_time) = date_trunc('day', '${set_my_time}'::TIMESTAMP)\r\n    GROUP BY 1 \r\n    ORDER BY 1\r\n) foreach on true;"
    }
   ]
  },
  {
   "title": "BERT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', update_time) as time, bert_status as status, count(*) as count_item\r\nfrom data_scm_tracking_ml\r\nWHERE bert_status in ('IN_US', 'COMPLETED', 'RETURN_TO_SENDER')\r\nGROUP BY time, status\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Update Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 6, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n\tupdate_time AS TIME,\n\ttracking_number AS \"Tracking number\",\n\tlstm_status AS \"LSTM Status\",\n\tbert_status AS \"BERT Status\" \nFROM\n\tdata_scm_tracking_ml \nORDER BY TIME DESC \nLIMIT 15"
    }
   ]
  },
  {
   "title": "Wrong order items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select date_trunc('day', update_time) as time, count(*) as \"number of wrong order items\"\r\nfrom data_scm_tracking_ml\r\nWHERE wrong_order=1\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "List of wrong order items",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select update_time as time, tracking_number as \"tracking_number\"\r\nfrom data_scm_tracking_ml\r\nWHERE wrong_order=1\r\norder by time desc\r\nLIMIT 20"
    }
   ]
  },
  {
   "title": "TrackLogs of ${tracking_number}",
   "type": "logs",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 38 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "Id:${tracking_number}",
     "timeField": "update_time"
    }
   ]
  }
 ]
}